### PR TITLE
Rebuild stdlib-list 0.8.0 for py311

### PR DESCRIPTION
**Pull request by skupr-anaconda**

### CODE REVIEW

**Review by akabanovs — COMMENTED** [review]
Should we address linter errors?

Build number not increased as you only going to upload for py3.11? Packages for other python versions will be removed before uploading?

**Comment by skupr-anaconda** [comment]
> Details

This build will create artifacts only for python 3.11 that's why I'm not bumping the build number. It won't affect other artifacts.
I would address linter errors when the new release will be issued

**Review by M-Waszkiewicz-Anaconda — APPROVED** [review]
LGTM

**Review by akabanovs — APPROVED** [review]
LGTM

**Pull request merged**
